//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoDeDados_Data_Grid_File.ServiceWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelamentoNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class CancelamentoNotaFiscalRequest : BancoDeDados_Data_Grid_File.ServiceWeb.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAutenticacaoField;
        
        private bool HomologacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroNotaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao {
            get {
                return this.ChaveAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAutenticacaoField, value) != true)) {
                    this.ChaveAutenticacaoField = value;
                    this.RaisePropertyChanged("ChaveAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Homologacao {
            get {
                return this.HomologacaoField;
            }
            set {
                if ((this.HomologacaoField.Equals(value) != true)) {
                    this.HomologacaoField = value;
                    this.RaisePropertyChanged("Homologacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroNota {
            get {
                return this.NumeroNotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroNotaField, value) != true)) {
                    this.NumeroNotaField = value;
                    this.RaisePropertyChanged("NumeroNota");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalLoteRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class EmissaoNotaFiscalLoteRequest : BancoDeDados_Data_Grid_File.ServiceWeb.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotasFiscaisLoteDTO NotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotasFiscaisLoteDTO Notas {
            get {
                return this.NotasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasField, value) != true)) {
                    this.NotasField = value;
                    this.RaisePropertyChanged("Notas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalLoteRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class ConsultaNotaFiscalLoteRequest : BancoDeDados_Data_Grid_File.ServiceWeb.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusNotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao {
            get {
                return this.ChaveAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAutenticacaoField, value) != true)) {
                    this.ChaveAutenticacaoField = value;
                    this.RaisePropertyChanged("ChaveAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLote {
            get {
                return this.CodigoLoteField;
            }
            set {
                if ((this.CodigoLoteField.Equals(value) != true)) {
                    this.CodigoLoteField = value;
                    this.RaisePropertyChanged("CodigoLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusNotas {
            get {
                return this.StatusNotasField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusNotasField, value) != true)) {
                    this.StatusNotasField = value;
                    this.RaisePropertyChanged("StatusNotas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class ConsultaNotaFiscalRequest : BancoDeDados_Data_Grid_File.ServiceWeb.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NumeroReciboFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NumeroReciboInicialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NumeroReciboUnicoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao {
            get {
                return this.ChaveAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAutenticacaoField, value) != true)) {
                    this.ChaveAutenticacaoField = value;
                    this.RaisePropertyChanged("ChaveAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinal {
            get {
                return this.DataFinalField;
            }
            set {
                if ((this.DataFinalField.Equals(value) != true)) {
                    this.DataFinalField = value;
                    this.RaisePropertyChanged("DataFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicial {
            get {
                return this.DataInicialField;
            }
            set {
                if ((this.DataInicialField.Equals(value) != true)) {
                    this.DataInicialField = value;
                    this.RaisePropertyChanged("DataInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboFinal {
            get {
                return this.NumeroReciboFinalField;
            }
            set {
                if ((this.NumeroReciboFinalField.Equals(value) != true)) {
                    this.NumeroReciboFinalField = value;
                    this.RaisePropertyChanged("NumeroReciboFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboInicial {
            get {
                return this.NumeroReciboInicialField;
            }
            set {
                if ((this.NumeroReciboInicialField.Equals(value) != true)) {
                    this.NumeroReciboInicialField = value;
                    this.RaisePropertyChanged("NumeroReciboInicial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroReciboUnico {
            get {
                return this.NumeroReciboUnicoField;
            }
            set {
                if ((this.NumeroReciboUnicoField.Equals(value) != true)) {
                    this.NumeroReciboUnicoField = value;
                    this.RaisePropertyChanged("NumeroReciboUnico");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalRequest", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class EmissaoNotaFiscalRequest : BancoDeDados_Data_Grid_File.ServiceWeb.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalDTO NotaFiscalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalDTO NotaFiscal {
            get {
                return this.NotaFiscalField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaFiscalField, value) != true)) {
                    this.NotaFiscalField = value;
                    this.RaisePropertyChanged("NotaFiscal");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteDTO))]
    public partial class NotaFiscalDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<decimal> AliquotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtividadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPPrestacaoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAutenticacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadePrestacaoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodObraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoPrestacaoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqptoReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoPrestacaoServicoField;
        
        private bool HomologacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformacoesAdicionaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NotaSubstituidaField;
        
        private bool NotificarTomadorPorEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCeiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NumeroReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SemIncidenciaISSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SimplesNacionalField;
        
        private bool SubstituicaoTributariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.PessoaDTO TomadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TomadorEstrangeiroField;
        
        private decimal ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorCSLLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorCofinsField;
        
        private System.Nullable<decimal> ValorDeducaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorINSSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorIRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorOutrosImpostosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorPisPasepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorRepasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nrExercicioReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> nrMesReferenciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Aliquota {
            get {
                return this.AliquotaField;
            }
            set {
                if ((this.AliquotaField.Equals(value) != true)) {
                    this.AliquotaField = value;
                    this.RaisePropertyChanged("Aliquota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Atividade {
            get {
                return this.AtividadeField;
            }
            set {
                if ((object.ReferenceEquals(this.AtividadeField, value) != true)) {
                    this.AtividadeField = value;
                    this.RaisePropertyChanged("Atividade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEPPrestacaoServico {
            get {
                return this.CEPPrestacaoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPPrestacaoServicoField, value) != true)) {
                    this.CEPPrestacaoServicoField = value;
                    this.RaisePropertyChanged("CEPPrestacaoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChaveAutenticacao {
            get {
                return this.ChaveAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAutenticacaoField, value) != true)) {
                    this.ChaveAutenticacaoField = value;
                    this.RaisePropertyChanged("ChaveAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CidadePrestacaoServico {
            get {
                return this.CidadePrestacaoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadePrestacaoServicoField, value) != true)) {
                    this.CidadePrestacaoServicoField = value;
                    this.RaisePropertyChanged("CidadePrestacaoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodObra {
            get {
                return this.CodObraField;
            }
            set {
                if ((object.ReferenceEquals(this.CodObraField, value) != true)) {
                    this.CodObraField = value;
                    this.RaisePropertyChanged("CodObra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRecibo {
            get {
                return this.DataReciboField;
            }
            set {
                if ((this.DataReciboField.Equals(value) != true)) {
                    this.DataReciboField = value;
                    this.RaisePropertyChanged("DataRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoPrestacaoServico {
            get {
                return this.EnderecoPrestacaoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoPrestacaoServicoField, value) != true)) {
                    this.EnderecoPrestacaoServicoField = value;
                    this.RaisePropertyChanged("EnderecoPrestacaoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqptoRecibo {
            get {
                return this.EqptoReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.EqptoReciboField, value) != true)) {
                    this.EqptoReciboField = value;
                    this.RaisePropertyChanged("EqptoRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoPrestacaoServico {
            get {
                return this.EstadoPrestacaoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoPrestacaoServicoField, value) != true)) {
                    this.EstadoPrestacaoServicoField = value;
                    this.RaisePropertyChanged("EstadoPrestacaoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Homologacao {
            get {
                return this.HomologacaoField;
            }
            set {
                if ((this.HomologacaoField.Equals(value) != true)) {
                    this.HomologacaoField = value;
                    this.RaisePropertyChanged("Homologacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InformacoesAdicionais {
            get {
                return this.InformacoesAdicionaisField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacoesAdicionaisField, value) != true)) {
                    this.InformacoesAdicionaisField = value;
                    this.RaisePropertyChanged("InformacoesAdicionais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NotaSubstituida {
            get {
                return this.NotaSubstituidaField;
            }
            set {
                if ((this.NotaSubstituidaField.Equals(value) != true)) {
                    this.NotaSubstituidaField = value;
                    this.RaisePropertyChanged("NotaSubstituida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool NotificarTomadorPorEmail {
            get {
                return this.NotificarTomadorPorEmailField;
            }
            set {
                if ((this.NotificarTomadorPorEmailField.Equals(value) != true)) {
                    this.NotificarTomadorPorEmailField = value;
                    this.RaisePropertyChanged("NotificarTomadorPorEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCDC {
            get {
                return this.NumeroCDCField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCDCField, value) != true)) {
                    this.NumeroCDCField = value;
                    this.RaisePropertyChanged("NumeroCDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCei {
            get {
                return this.NumeroCeiField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCeiField, value) != true)) {
                    this.NumeroCeiField = value;
                    this.RaisePropertyChanged("NumeroCei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroRecibo {
            get {
                return this.NumeroReciboField;
            }
            set {
                if ((this.NumeroReciboField.Equals(value) != true)) {
                    this.NumeroReciboField = value;
                    this.RaisePropertyChanged("NumeroRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SemIncidenciaISS {
            get {
                return this.SemIncidenciaISSField;
            }
            set {
                if ((this.SemIncidenciaISSField.Equals(value) != true)) {
                    this.SemIncidenciaISSField = value;
                    this.RaisePropertyChanged("SemIncidenciaISS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SimplesNacional {
            get {
                return this.SimplesNacionalField;
            }
            set {
                if ((this.SimplesNacionalField.Equals(value) != true)) {
                    this.SimplesNacionalField = value;
                    this.RaisePropertyChanged("SimplesNacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SubstituicaoTributaria {
            get {
                return this.SubstituicaoTributariaField;
            }
            set {
                if ((this.SubstituicaoTributariaField.Equals(value) != true)) {
                    this.SubstituicaoTributariaField = value;
                    this.RaisePropertyChanged("SubstituicaoTributaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.PessoaDTO Tomador {
            get {
                return this.TomadorField;
            }
            set {
                if ((object.ReferenceEquals(this.TomadorField, value) != true)) {
                    this.TomadorField = value;
                    this.RaisePropertyChanged("Tomador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TomadorEstrangeiro {
            get {
                return this.TomadorEstrangeiroField;
            }
            set {
                if ((this.TomadorEstrangeiroField.Equals(value) != true)) {
                    this.TomadorEstrangeiroField = value;
                    this.RaisePropertyChanged("TomadorEstrangeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorCSLL {
            get {
                return this.ValorCSLLField;
            }
            set {
                if ((this.ValorCSLLField.Equals(value) != true)) {
                    this.ValorCSLLField = value;
                    this.RaisePropertyChanged("ValorCSLL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorCofins {
            get {
                return this.ValorCofinsField;
            }
            set {
                if ((this.ValorCofinsField.Equals(value) != true)) {
                    this.ValorCofinsField = value;
                    this.RaisePropertyChanged("ValorCofins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> ValorDeducao {
            get {
                return this.ValorDeducaoField;
            }
            set {
                if ((this.ValorDeducaoField.Equals(value) != true)) {
                    this.ValorDeducaoField = value;
                    this.RaisePropertyChanged("ValorDeducao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorINSS {
            get {
                return this.ValorINSSField;
            }
            set {
                if ((this.ValorINSSField.Equals(value) != true)) {
                    this.ValorINSSField = value;
                    this.RaisePropertyChanged("ValorINSS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorIR {
            get {
                return this.ValorIRField;
            }
            set {
                if ((this.ValorIRField.Equals(value) != true)) {
                    this.ValorIRField = value;
                    this.RaisePropertyChanged("ValorIR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorOutrosImpostos {
            get {
                return this.ValorOutrosImpostosField;
            }
            set {
                if ((this.ValorOutrosImpostosField.Equals(value) != true)) {
                    this.ValorOutrosImpostosField = value;
                    this.RaisePropertyChanged("ValorOutrosImpostos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorPisPasep {
            get {
                return this.ValorPisPasepField;
            }
            set {
                if ((this.ValorPisPasepField.Equals(value) != true)) {
                    this.ValorPisPasepField = value;
                    this.RaisePropertyChanged("ValorPisPasep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ValorRepasse {
            get {
                return this.ValorRepasseField;
            }
            set {
                if ((this.ValorRepasseField.Equals(value) != true)) {
                    this.ValorRepasseField = value;
                    this.RaisePropertyChanged("ValorRepasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrExercicioReferencia {
            get {
                return this.nrExercicioReferenciaField;
            }
            set {
                if ((this.nrExercicioReferenciaField.Equals(value) != true)) {
                    this.nrExercicioReferenciaField = value;
                    this.RaisePropertyChanged("nrExercicioReferencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> nrMesReferencia {
            get {
                return this.nrMesReferenciaField;
            }
            set {
                if ((this.nrMesReferenciaField.Equals(value) != true)) {
                    this.nrMesReferenciaField = value;
                    this.RaisePropertyChanged("nrMesReferencia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotasFiscaisLoteDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    public partial class NotasFiscaisLoteDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ChaveAutenticacaoField;
        
        private string EmailContatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteDTO[] NotasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ChaveAutenticacao {
            get {
                return this.ChaveAutenticacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAutenticacaoField, value) != true)) {
                    this.ChaveAutenticacaoField = value;
                    this.RaisePropertyChanged("ChaveAutenticacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmailContato {
            get {
                return this.EmailContatoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailContatoField, value) != true)) {
                    this.EmailContatoField = value;
                    this.RaisePropertyChanged("EmailContato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteDTO[] Notas {
            get {
                return this.NotasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasField, value) != true)) {
                    this.NotasField = value;
                    this.RaisePropertyChanged("Notas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalLoteDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    public partial class NotaFiscalLoteDTO : BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contri" +
        "buinte")]
    [System.SerializableAttribute()]
    public partial class PessoaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DDDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.EnderecoDTO EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoMunicipalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJ {
            get {
                return this.CNPJField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJField, value) != true)) {
                    this.CNPJField = value;
                    this.RaisePropertyChanged("CNPJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DDD {
            get {
                return this.DDDField;
            }
            set {
                if ((object.ReferenceEquals(this.DDDField, value) != true)) {
                    this.DDDField = value;
                    this.RaisePropertyChanged("DDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.EnderecoDTO Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InscricaoMunicipal {
            get {
                return this.InscricaoMunicipalField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoMunicipalField, value) != true)) {
                    this.InscricaoMunicipalField = value;
                    this.RaisePropertyChanged("InscricaoMunicipal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnderecoDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Contri" +
        "buinte")]
    [System.SerializableAttribute()]
    public partial class EnderecoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoLogradouroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoLogradouro {
            get {
                return this.TipoLogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoLogradouroField, value) != true)) {
                    this.TipoLogradouroField = value;
                    this.RaisePropertyChanged("TipoLogradouro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemErroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((this.ErroField.Equals(value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro {
            get {
                return this.MensagemErroField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemErroField, value) != true)) {
                    this.MensagemErroField = value;
                    this.RaisePropertyChanged("MensagemErro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelamentoNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class CancelamentoNotaFiscalResponse : BancoDeDados_Data_Grid_File.ServiceWeb.ResponseBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalLoteResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class EmissaoNotaFiscalLoteResponse : BancoDeDados_Data_Grid_File.ServiceWeb.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalLoteResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class ConsultaNotaFiscalLoteResponse : BancoDeDados_Data_Grid_File.ServiceWeb.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContadorNotasErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContadorNotasGeradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataFinalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataInicioProcessamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteGeradaDTO[] NotasGeradasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoLote {
            get {
                return this.CodigoLoteField;
            }
            set {
                if ((this.CodigoLoteField.Equals(value) != true)) {
                    this.CodigoLoteField = value;
                    this.RaisePropertyChanged("CodigoLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContadorNotasErro {
            get {
                return this.ContadorNotasErroField;
            }
            set {
                if ((this.ContadorNotasErroField.Equals(value) != true)) {
                    this.ContadorNotasErroField = value;
                    this.RaisePropertyChanged("ContadorNotasErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContadorNotasGeradas {
            get {
                return this.ContadorNotasGeradasField;
            }
            set {
                if ((this.ContadorNotasGeradasField.Equals(value) != true)) {
                    this.ContadorNotasGeradasField = value;
                    this.RaisePropertyChanged("ContadorNotasGeradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEnvio {
            get {
                return this.DataEnvioField;
            }
            set {
                if ((this.DataEnvioField.Equals(value) != true)) {
                    this.DataEnvioField = value;
                    this.RaisePropertyChanged("DataEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataFinalizacao {
            get {
                return this.DataFinalizacaoField;
            }
            set {
                if ((this.DataFinalizacaoField.Equals(value) != true)) {
                    this.DataFinalizacaoField = value;
                    this.RaisePropertyChanged("DataFinalizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataInicioProcessamento {
            get {
                return this.DataInicioProcessamentoField;
            }
            set {
                if ((this.DataInicioProcessamentoField.Equals(value) != true)) {
                    this.DataInicioProcessamentoField = value;
                    this.RaisePropertyChanged("DataInicioProcessamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteGeradaDTO[] NotasGeradas {
            get {
                return this.NotasGeradasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasGeradasField, value) != true)) {
                    this.NotasGeradasField = value;
                    this.RaisePropertyChanged("NotasGeradas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class ConsultaNotaFiscalResponse : BancoDeDados_Data_Grid_File.ServiceWeb.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataFinalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalConsultaDTO[] NotasGeradasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtdeNotasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEnvio {
            get {
                return this.DataEnvioField;
            }
            set {
                if ((this.DataEnvioField.Equals(value) != true)) {
                    this.DataEnvioField = value;
                    this.RaisePropertyChanged("DataEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataFinalizacao {
            get {
                return this.DataFinalizacaoField;
            }
            set {
                if ((this.DataFinalizacaoField.Equals(value) != true)) {
                    this.DataFinalizacaoField = value;
                    this.RaisePropertyChanged("DataFinalizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalConsultaDTO[] NotasGeradas {
            get {
                return this.NotasGeradasField;
            }
            set {
                if ((object.ReferenceEquals(this.NotasGeradasField, value) != true)) {
                    this.NotasGeradasField = value;
                    this.RaisePropertyChanged("NotasGeradas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QtdeNotas {
            get {
                return this.QtdeNotasField;
            }
            set {
                if ((this.QtdeNotasField.Equals(value) != true)) {
                    this.QtdeNotasField = value;
                    this.RaisePropertyChanged("QtdeNotas");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmissaoNotaFiscalResponse", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Negocio.WebServices.Mensagem")]
    [System.SerializableAttribute()]
    public partial class EmissaoNotaFiscalResponse : BancoDeDados_Data_Grid_File.ServiceWeb.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalGeradaDTO NotaFiscalGeradaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalGeradaDTO NotaFiscalGerada {
            get {
                return this.NotaFiscalGeradaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaFiscalGeradaField, value) != true)) {
                    this.NotaFiscalGeradaField = value;
                    this.RaisePropertyChanged("NotaFiscalGerada");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalGeradaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalLoteGeradaDTO))]
    public partial class NotaFiscalGeradaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutenticadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autenticador {
            get {
                return this.AutenticadorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutenticadorField, value) != true)) {
                    this.AutenticadorField = value;
                    this.RaisePropertyChanged("Autenticador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalLoteGeradaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    public partial class NotaFiscalLoteGeradaDTO : BancoDeDados_Data_Grid_File.ServiceWeb.NotaFiscalGeradaDTO {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquipamentoReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemErroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReciboField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipamentoRecibo {
            get {
                return this.EquipamentoReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.EquipamentoReciboField, value) != true)) {
                    this.EquipamentoReciboField = value;
                    this.RaisePropertyChanged("EquipamentoRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((this.ErroField.Equals(value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensagemErro {
            get {
                return this.MensagemErroField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemErroField, value) != true)) {
                    this.MensagemErroField = value;
                    this.RaisePropertyChanged("MensagemErro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recibo {
            get {
                return this.ReciboField;
            }
            set {
                if ((object.ReferenceEquals(this.ReciboField, value) != true)) {
                    this.ReciboField = value;
                    this.RaisePropertyChanged("Recibo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotaFiscalConsultaDTO", Namespace="http://schemas.datacontract.org/2004/07/Eissnfe.Dominio.DataTransferObject.Presta" +
        "dor")]
    [System.SerializableAttribute()]
    public partial class NotaFiscalConsultaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AliquotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodAtividadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CodObraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAutenticidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataCancelamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataEmissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DataReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocTomadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoPrestacaoServicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkNFEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotivoCancelamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeTomadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NossoNumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NumeroReciboField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SubstituicaoTributariaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorIssField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorNFEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Aliquota {
            get {
                return this.AliquotaField;
            }
            set {
                if ((this.AliquotaField.Equals(value) != true)) {
                    this.AliquotaField = value;
                    this.RaisePropertyChanged("Aliquota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAtividade {
            get {
                return this.CodAtividadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAtividadeField, value) != true)) {
                    this.CodAtividadeField = value;
                    this.RaisePropertyChanged("CodAtividade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodObra {
            get {
                return this.CodObraField;
            }
            set {
                if ((this.CodObraField.Equals(value) != true)) {
                    this.CodObraField = value;
                    this.RaisePropertyChanged("CodObra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoAutenticidade {
            get {
                return this.CodigoAutenticidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAutenticidadeField, value) != true)) {
                    this.CodigoAutenticidadeField = value;
                    this.RaisePropertyChanged("CodigoAutenticidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataCancelamento {
            get {
                return this.DataCancelamentoField;
            }
            set {
                if ((this.DataCancelamentoField.Equals(value) != true)) {
                    this.DataCancelamentoField = value;
                    this.RaisePropertyChanged("DataCancelamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataEmissao {
            get {
                return this.DataEmissaoField;
            }
            set {
                if ((this.DataEmissaoField.Equals(value) != true)) {
                    this.DataEmissaoField = value;
                    this.RaisePropertyChanged("DataEmissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRecibo {
            get {
                return this.DataReciboField;
            }
            set {
                if ((this.DataReciboField.Equals(value) != true)) {
                    this.DataReciboField = value;
                    this.RaisePropertyChanged("DataRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocTomador {
            get {
                return this.DocTomadorField;
            }
            set {
                if ((object.ReferenceEquals(this.DocTomadorField, value) != true)) {
                    this.DocTomadorField = value;
                    this.RaisePropertyChanged("DocTomador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnderecoPrestacaoServico {
            get {
                return this.EnderecoPrestacaoServicoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoPrestacaoServicoField, value) != true)) {
                    this.EnderecoPrestacaoServicoField = value;
                    this.RaisePropertyChanged("EnderecoPrestacaoServico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkNFE {
            get {
                return this.LinkNFEField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkNFEField, value) != true)) {
                    this.LinkNFEField = value;
                    this.RaisePropertyChanged("LinkNFE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoCancelamento {
            get {
                return this.MotivoCancelamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MotivoCancelamentoField, value) != true)) {
                    this.MotivoCancelamentoField = value;
                    this.RaisePropertyChanged("MotivoCancelamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeTomador {
            get {
                return this.NomeTomadorField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeTomadorField, value) != true)) {
                    this.NomeTomadorField = value;
                    this.RaisePropertyChanged("NomeTomador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NossoNumero {
            get {
                return this.NossoNumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NossoNumeroField, value) != true)) {
                    this.NossoNumeroField = value;
                    this.RaisePropertyChanged("NossoNumero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NumeroRecibo {
            get {
                return this.NumeroReciboField;
            }
            set {
                if ((this.NumeroReciboField.Equals(value) != true)) {
                    this.NumeroReciboField = value;
                    this.RaisePropertyChanged("NumeroRecibo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SubstituicaoTributaria {
            get {
                return this.SubstituicaoTributariaField;
            }
            set {
                if ((this.SubstituicaoTributariaField.Equals(value) != true)) {
                    this.SubstituicaoTributariaField = value;
                    this.RaisePropertyChanged("SubstituicaoTributaria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorIss {
            get {
                return this.ValorIssField;
            }
            set {
                if ((this.ValorIssField.Equals(value) != true)) {
                    this.ValorIssField = value;
                    this.RaisePropertyChanged("ValorIss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorNFE {
            get {
                return this.ValorNFEField;
            }
            set {
                if ((this.ValorNFEField.Equals(value) != true)) {
                    this.ValorNFEField = value;
                    this.RaisePropertyChanged("ValorNFE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceWeb.INotaFiscalEletronicaServico")]
    public interface INotaFiscalEletronicaServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Emitir", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirResponse")]
        BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalResponse Emitir(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Emitir", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirResponse")]
        System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalResponse> EmitirAsync(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/CancelarResponse")]
        BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalResponse Cancelar(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Cancelar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/CancelarResponse")]
        System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalResponse> CancelarAsync(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLoteResponse")]
        BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteResponse EmitirEmLote(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/EmitirEmLoteResponse")]
        System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteResponse> EmitirEmLoteAsync(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLoteResponse")]
        BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteResponse ConsultarLote(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLote", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarLoteResponse")]
        System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteResponse> ConsultarLoteAsync(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Consultar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarResponse")]
        BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalResponse Consultar(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotaFiscalEletronicaServico/Consultar", ReplyAction="http://tempuri.org/INotaFiscalEletronicaServico/ConsultarResponse")]
        System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalResponse> ConsultarAsync(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotaFiscalEletronicaServicoChannel : BancoDeDados_Data_Grid_File.ServiceWeb.INotaFiscalEletronicaServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotaFiscalEletronicaServicoClient : System.ServiceModel.ClientBase<BancoDeDados_Data_Grid_File.ServiceWeb.INotaFiscalEletronicaServico>, BancoDeDados_Data_Grid_File.ServiceWeb.INotaFiscalEletronicaServico {
        
        public NotaFiscalEletronicaServicoClient() {
        }
        
        public NotaFiscalEletronicaServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotaFiscalEletronicaServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalEletronicaServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalEletronicaServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalResponse Emitir(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalRequest request) {
            return base.Channel.Emitir(request);
        }
        
        public System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalResponse> EmitirAsync(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalRequest request) {
            return base.Channel.EmitirAsync(request);
        }
        
        public BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalResponse Cancelar(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalRequest request) {
            return base.Channel.Cancelar(request);
        }
        
        public System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalResponse> CancelarAsync(BancoDeDados_Data_Grid_File.ServiceWeb.CancelamentoNotaFiscalRequest request) {
            return base.Channel.CancelarAsync(request);
        }
        
        public BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteResponse EmitirEmLote(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteRequest request) {
            return base.Channel.EmitirEmLote(request);
        }
        
        public System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteResponse> EmitirEmLoteAsync(BancoDeDados_Data_Grid_File.ServiceWeb.EmissaoNotaFiscalLoteRequest request) {
            return base.Channel.EmitirEmLoteAsync(request);
        }
        
        public BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteResponse ConsultarLote(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteRequest request) {
            return base.Channel.ConsultarLote(request);
        }
        
        public System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteResponse> ConsultarLoteAsync(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalLoteRequest request) {
            return base.Channel.ConsultarLoteAsync(request);
        }
        
        public BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalResponse Consultar(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalRequest request) {
            return base.Channel.Consultar(request);
        }
        
        public System.Threading.Tasks.Task<BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalResponse> ConsultarAsync(BancoDeDados_Data_Grid_File.ServiceWeb.ConsultaNotaFiscalRequest request) {
            return base.Channel.ConsultarAsync(request);
        }
    }
}
